vich_uploader:
    db_driver: orm
    mappings:
        cv_files:
            uri_prefix: /uploads/cvs
            upload_destination: '%kernel.project_dir%/public/uploads/cvs'
            namer: Vich\UploaderBundle\Naming\UniqidNamer